=head1 NAME

simplevisor 0.9 - simple daemons supervisor

=head1 SYNOPSIS

B<simplevisor>
[--conf CONF][--daemon][--interval INTERVAL][-h][--log LOG][--logfile LOGFILE][--loglevel LOGLEVEL][--logname LOGNAME][-p PIDFILE][--store STORE][--version]
command [path]

=head1 DESCRIPTION

Simplevisor is a simple daemons supervisor, it is inspired
by Erlang OTP and it can supervise hierarchies of services.

COMMANDS

If a path is given or only one service entry is given:

for given command X
    run the service X command where service is the only entry provided
    or the entry identified by its path

If path is not given and root entry is a supervisor:

start
    start the simplevisor process which start the supervision.
    It can be used with --daemon if you want it as daemon

stop
    stop the simplevisor process and all its children, if running

status
    return the status of the simplevisor process

check
    return the comparison between the expected state and the actual state.
    0 -> everything is fine
    1 -> warning, not expected

restart
    stop + start the simplevisor process

single
    execute one cycle of supervision and exit.
    Useful to be run in a cron script

stop_supervisor
    stop only the simplevisor process and the supervision

stop_children
    stop only the children

check_configuration
    only check the configuration file

pod
    generate pod format help to be used by pod2man to generate man page

rst
    generate rst format help to be used in the web doc

help
    same as -h/--help, print help page




=head1 OPTIONS

B<positional arguments:>

=over

B<command> check, check_configuration, help, pod, restart, rst, single, start, status, stop, stop_children, stop_supervisor

B<path> path to a service, subset of commands available: start, stop, status, check, restart


=back

B<optional arguments:>

=over


B<--conf CONF> configuration file

B<--daemon> daemonize, ONLY with start

B<--interval INTERVAL> interval to wait between supervision cycles (default: 60)

B<-h, --help> print the help page

B<--log LOG> available: null, file, syslog, stdout (default: stdout)

B<--logfile LOGFILE> log file, ONLY for file

B<--loglevel LOGLEVEL> log level (default: warning)

B<--logname LOGNAME> log name (default: simplevisor)

B<-p, --pidfile PIDFILE> the pidfile

B<--store STORE> file where to store the state, it is not mandatory,however recommended to store the simplevisor nodes status between restarts

B<--version> print the program version


=back

=head1 EXAMPLES

Create and edit the main configuration file:

    ## look for simplevisor.conf.example in the examples.

Run it:

    simplevisor --conf /path/to/simplevisor.conf start

to run it in daemon mode:

    simplevisor --conf /path/to/simplevisor.conf --daemon start

For other commands:

    simplevisor --help

Given the example configuration, to start the httpd service:

    simplevisor --conf /path/to/simplevisor.conf start svisor1/httpd


=head1 AUTHOR

Massimo Paladin <massimo.paladin@gmail.com>

Copyright (C) CERN 2013-2014


