#notifications:
#  email:
#    - mig-travis@cern.ch
language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# install cpanminus
before_install:
  - sudo apt-get update
  - sudo apt-get install cpanminus -y
# command to install dependencies
install:
  - sudo cpanm -v --notest --mirror http://cpan.mirrors.travis-ci.org No::Worries
  - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install simplejson --use-mirrors; fi
  - pip install argparse --use-mirrors || echo "no needed from 3.2 on, ok"
  - pip install pep8 --use-mirrors
# command to run tests
script:
  - pep8 simplevisor/ bin/simplevisor test/
  - python setup.py install --no-data-files
  - python setup.py test
