language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - pip install simplejson --use-mirrors || echo "ok"
  - pip install argparse --use-mirrors || echo "ok"
# command to run tests
script:
  - python setup.py test
  - python setup.py install --no-data-files
