notifications:
  email:
    - mig-travis@cern.ch
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# install cpanminus
before_install:
  - sudo apt-get update
  - sudo apt-get install cpanminus -y
# command to install dependencies
install:
  - sudo cpanm -v --notest No::Worries
  - pip install --use-mirrors argparse || echo "no needed from 3.2 on, ok"
  - pip install --use-mirrors pep8
  - pip install --use-mirrors pylint
  - curl -O -R -S -f -s https://raw.github.com/cern-mig/dev-tools/master/python/pylint.sh
  - curl -O -R -S -f -s https://raw.github.com/cern-mig/dev-tools/master/python/.pylintrc
# command to run tests
script:
  - pep8 simplevisor bin/simplevisor test
  - sh pylint.sh simplevisor bin/simplevisor test || echo "*ignored*"
  - python setup.py install
  - python setup.py test
