notifications:
  email:
    - mig-travis@cern.ch
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# install cpanminus
before_install:
  - sudo apt-get update
  - sudo apt-get install cpanminus -y
# command to install dependencies
install:
  - sudo cpanm -v --notest No::Worries
  - pip install argparse || echo "no needed from 3.2 onward, ok"
  - pip install pycodestyle
  - pip install pylint
  - curl -O -R -S -f -s https://raw.github.com/cern-mig/dev-tools/master/python/pylint.sh
  - curl -O -R -S -f -s https://raw.github.com/cern-mig/dev-tools/master/python/.pylintrc
# command to run tests
script:
  - pycodestyle simplevisor bin/simplevisor test
  - sh pylint.sh simplevisor bin/simplevisor test || echo "*ignored*"
  - python setup.py install
  - python setup.py test
