name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout dev-tools
        uses: actions/checkout@v4
        with:
          repository: cern-mig/dev-tools
          path: ./dev-tools
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (Perl)
        uses: perl-actions/install-with-cpm@stable
        with:
          install: No::Worries
      - name: Install dependencies (Python)
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle pylint
          pip install argparse || echo "ok"
      - name: Lint with pycodestyle
        run: |
          pycodestyle simplevisor bin/simplevisor test
      - name: Lint with pylint
        run: |
          pylint --exit-zero --rcfile dev-tools/python/.pylintrc simplevisor bin/simplevisor test
      - name: Test
        run: |
          python setup.py install
          python setup.py test
